apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bubble-sort
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
        - image: dev.local/bubble-sort:1.0.0
