apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bubble-sort
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "hpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "cpu"
        autoscaling.knative.dev/target: "90"

        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "5"

        autoscaling.knative.dev/window: "10s"
    spec:
      containers:
        - image: dev.local/bubble-sort:1.0.0
