apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fibonacci-n-pod-optimal
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # TODO: distribute loads to pods with new data
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "350"

        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "12"

        # # Stable window
        # autoscaling.knative.dev/window: "60s"

        # # Make panic window x% of stable window
        # autoscaling.knative.dev/panic-window-percentage: "1.0"

        autoscaling.knative.dev/window: "6s"

        # Make all requests are handled by the activator (always active)
        # try turning this off so requests can go to container directly
        autoscaling.knative.dev/target-burst-capacity: "-1"

        # If current concurrency is x% of target, scale up (accommodate containerCreating)
        autoscaling.knative.dev/target-utilization-percentage: "50"

        # # Make 3 pods when scaling from zero
        # autoscaling.knative.dev/activation-scale: "4"
    spec:
      containerConcurrency: 350
      containers:
        - image: dev.local/fibonacci:1.0.0
          resources:
            requests:
              cpu: 100m
              memory: 128m
            limits:
              cpu: 300m
              memory: 512M
