apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fibonacci
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "hpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "cpu"
        autoscaling.knative.dev/target: "20"

        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "5"

        autoscaling.knative.dev/window: "6s"
    spec:
      containers:
        - image: dev.local/fibonacci:1.0.0
          resources:
            requests:
              cpu: 100m
              memory: 512M
            limits:
              cpu: 500m
              memory: 512M
