server:
  enabled: false
  ## namespaces to monitor (instead of monitoring all - clusterwide).
  namespaces:
    - default
  global:
    ## How frequently to scrape targets by default
    scrape_interval: 1m
    ## How long until a scrape request times out
    scrape_timeout: 10s
    ## How frequently to evaluate rules
    evaluation_interval: 1m
  service:
    enabled: true
    servicePort: 80
    nodePort: 32258
    type: NodePort
  resources: 
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true

prometheus-node-exporter:
  enabled: true

alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

