apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vite-knative-svc
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/syakhisk/vite-knative
          env:
            - name: TARGET
              value: "Node.js Sample v1"
