version: "3"

services:
  # caddy:
  #   container_name: caddy
  #   image: caddy:2.6.4-alpine
  #   network_mode: host
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - caddy_data:/data
  #   restart: unless-stopped
  webserver:
    image: nginx:1.25.1-alpine
    container_name: nginx
    network_mode: host
    restart: unless-stopped
    tty: true
    volumes:
      - ./nginx.default.conf:/etc/nginx/templates/default.conf.template

# volumes:
#   caddy_data:
