apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: is-prime
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: dev.local/is-prime:1.0.0
        env:
        - name: TARGET
          value: "Node.js Sample v1"
