apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fibonacci
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "840"

        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "10"

        autoscaling.knative.dev/window: "10s"
    spec:
      containers:
        - image: dev.local/fibonacci:1.0.0
          resources:
            requests:
              cpu: 100m
              memory: 512M
            limits:
              cpu: 1
              memory: 512M
