apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-nodejs
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: dev.local/helloworld-nodejs:1.0.0
          imagePullPolicy: Never
          env:
            - name: TARGET
              value: "Node.js Sample v1"
