apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fibonacci-1-to-5-pod
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "1300"

        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "5"

        autoscaling.knative.dev/window: "6s"
    spec:
      containers:
        - image: dev.local/fibonacci:1.0.0
          resources:
            requests:
              cpu: 200m
              memory: 200M
            limits:
              cpu: 250m
              memory: 300M
