version: "3.9"
services:
  nginx:
    image: nginx:1.23.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "8080:80"
    environment:
     - NGINX_PORT=80
    # command: [nginx-debug, '-g', 'daemon off;']
  web-server:
    container_name: web-server
    image: python:3.11-alpine
    command: [python, '-m', 'http.server']

# volumes:
#   reverse-proxy-volume:
