apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go-go-go
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: dev.local/helloworld-go-go-go:latest
        imagePullPolicy: Never
        env:
        - name: TARGET
          value: "Go Sample v1"
